window.sss = window.sss || {};

window.sss.features = [
    {"key":11,"values":["led light","l.e.d.","lighting"]},
    {"key":24,"values":["portable"]},
    {"key":36,"values":["color chang"]},
    {"key":37,"values":["legs"]},
    {"key":38,"values":["adjustable flame"]},
    {"key":39,"values":["weather resistant"]},
    {"key":40,"values":["cover included", "includes cover"]},
    {"key":41,"values":["mosquito net"]},
    {"key":42,"values":["enclosed"]},
    {"key":43,"values":["retractable"]},
    {"key":44,"values":["adjustable height"]},
    {"key":45,"values":["covered"]},
    {"key":46,"values":["water proof","waterproof","water-proof"]},
    {"key":48,"values":["sloped"]},
    {"key":49,"values":["attached"]},
    {"key":50,"values":["freestanding"]},
    {"key":51,"values":["stringer"]},
    {"key":52,"values":["retractable shade"]},
    {"key":53,"values":["privacy wall"]},
    {"key":54,"values":["curtain"]},
    {"key":55,"values":["folding"]},
    {"key":56,"values":["stacking","stackable","stacks","stack quantity","nest quantity"]},
    {"key":57,"values":["reclin"]},
    {"key":58,"values":["uv protected"]},
    {"key":59,"values":["includles fire pit"]},
    {"key":60,"values":["eco friendly"]},
    {"key":61,"values":["solid wood"]},
    {"key":62,"values":["arm ","arms"]},
    {"key":63,"values":["has storage"]},
    {"key":64,"values":["powder coat","powder-coat"]},
    {"key":65,"values":["swiveling","swivel "]},
    {"key":66,"values":["rocking","rocker"]},
    {"key":67,"values":["cushioned","cushion ","padded", "pad "]},
    {"key":68,"values":["wind guard"]},
    {"key":69,"values":["multi-canopy","multi canopy"]},
    {"key":70,"values":["tilting","tilts"]},
    {"key":71,"values":["fixed base"]},
    {"key":72,"values":["mobile base","mobile"]},
    {"key":73,"values":["cantilever"]},
    {"key":76,"values":["gliding","glider"]},
    {"key":94,"values":["ada compliant","ada-compliant"]},
    {"key":95,"values":["wheels"]},
    {"key":96,"values":["umbrella hole", "hole for umbrella"]},
];

window.sss.categoryTypes = [
    {"key" : 11, "values" :	["fire pit"]},
    {"key" : 12, "values" :	["chimenea"]},
    {"key" : 13, "values" :	["fire table"]},
    {"key" : 20, "values" :	["fire ring"]},
    {"key" : 21, "values" :	["fire column"]},
    {"key" : 22, "values" :	["fire bowl"]},
    {"key" : 23, "values" :	["canopie"]},
    {"key" : 24, "values" :	["gazebo"]},
    {"key" : 25, "values" :	["pergola"]},
    {"key" : 26, "values" :	["arbor"]},
    {"key" : 27, "values" :	["burners & kit","burners and kit"]},
    {"key" : 28, "values" :	["table & chair set","table and chair set"]},
    {"key" : 29, "values" :	["bench"]},
    {"key" : 30, "values" :	["sofa set"]},
    {"key" : 31, "values" :	["outdoor pillow"]},
    {"key" : 32, "values" :	["table"]},
    {"key" : 33, "values" :	["sofa","sectional","module","section"]},
    {"key" : 34, "values" :	["daybed","chaise"]},
    {"key" : 35, "values" :	["ottoman"]},
    {"key" : 36, "values" :	["porch swing"]},
    {"key" : 37, "values" :	["chair set"]},
    {"key" : 38, "values" :	["chair","rocker","lounger"]},
    {"key" : 39, "values" :	["stool"]},
    {"key" : 40, "values" :	["settee"]},
    {"key" : 41, "values" :	["sideboard","credenza"]},
    {"key" : 42, "values" :	["dining chair"]},
    {"key" : 43, "values" :	["lounge chair", "lounger"]},
    {"key" : 44, "values" :	["loveseat","love seat"]},
    {"key" : 45, "values" :	["rocking chair","rocker"]},
    {"key" : 46, "values" :	["side chair"]},
    {"key" : 47, "values" :	["glider","gliding"]},
    {"key" : 48, "values" :	["counter stool"]},
    {"key" : 49, "values" :	["bar stool"]},
    {"key" : 50, "values" :	["end table"]},
    {"key" : 51, "values" :	["entertainment unit"]},
    {"key" : 52, "values" :	["occasional table"]},
    {"key" : 53, "values" :	["dining table","dining umbrella table"]},
    {"key" : 54, "values" :	["counter table"]},
    {"key" : 55, "values" :	["bar table"]},
    {"key" : 56, "values" :	["coffee table"]},
    {"key" : 57, "values" :	["adirondack"]},
    {"key" : 59, "values" :	["arm chair"]},
    {"key" : 60, "values" :	["lazy susan"]},
    {"key" : 61, "values" :	["footrest"]},
    {"key" : 63, "values" :	["stacking table"]},
    {"key" : 64, "values" :	["bistro table"]},
    {"key" : 65, "values" :	["chat table"]},
    {"key" : 66, "values" :	["rail table"]},
    {"key" : 67, "values" :	["lamp table"]},
    {"key" : 68, "values" :	["bistro chair"]},
    {"key" : 69, "values" :	["console table"]},
    {"key" : 75, "values" :	["tea table"]},
    {"key" : 76, "values" :	["umbrella table"]},
    {"key" : 77, "values" :	["ada table"]},
    {"key" : 78, "values" :	["club chair"]},
    {"key" : 79, "values" :	["recliner"]},
    {"key" : 80, "values" :	["spa chair"]},
    {"key" : 81, "values" :	["sand chair"]},
    {"key" : 82, "values" :	["cabana"]},
    {"key" : 83, "values" :	["module"]},
    {"key" : 84, "values" :	["picnic table"]},
    {"key" : 85, "values" :	["spanner table"]},
];

window.sss.frameMaterials = [
    {"key": 1, "values":	["aluminum"]},
    {"key": 2, "values":	["steel"]},
    {"key": 3, "values":	["cedar"]},
    {"key": 4, "values":	["vinyl"]},
    {"key": 5, "values":	["iron"]},
    {"key": 6, "values":	["wood"]},
    {"key": 7, "values":	["metal"]},
    {"key": 8, "values":	["plastic"]},
    {"key": 9, "values":	["aluminum"]},
    {"key": 10, "values":	["steel"]},
    {"key": 11, "values":	["cedar"]},
    {"key": 12, "values":	["cast iron"]},
    {"key": 13, "values":	["wrought iron"]},
    {"key": 14, "values":	["wood"]},
    {"key": 15, "values":	["teak"]},
    {"key": 16, "values":	["plastic"]},
    {"key": 17, "values":	["acacia"]},
    {"key": 18, "values":	["mixed materials"]},
    {"key": 19, "values":	["aluminum"]},
    {"key": 20, "values":	["steel"]},
    {"key": 21, "values":	["cedar"]},
    {"key": 22, "values":	["cast iron"]},
    {"key": 23, "values":	["wrought iron"]},
    {"key": 24, "values":	["wood"]},
    {"key": 25, "values":	["teak"]},
    {"key": 26, "values":	["plastic"]},
    {"key": 27, "values":	["acacia"]},
    {"key": 28, "values":	["mixed materials"]},
    {"key": 29, "values":	["ipe"]},
    {"key": 30, "values":	[" iron"]},
    {"key": 31, "values":	["polymer","rotoform","acrylic"]},
    {"key": 32, "values":	["cast aluminum","cast-aluminum"]},
];

window.sss.shapes = [
    {"key":7,"values":["rectangle"]},
    {"key":8,"values":["octagon"]},
    {"key":9,"values":["square"]},
    {"key":10,"values":["round","circular"]},
    {"key":22,"values":["oval"]},
    {"key":23,"values":["arch"]},
    {"key":24,"values":["rectangle"]},
    {"key":25,"values":["square"]},
    {"key":26,"values":["linear"]},
    {"key":27,"values":["portrait"]},
    {"key":28,"values":["pentagon"]},
    {"key":29,"values":["rectangular"]},
    {"key":30,"values":["round","circular"]},
    {"key":31,"values":["hexagon"]},
    {"key":32,"values":["oval"]},
    {"key":33,"values":["linear"]},
    {"key":34,"values":["rectangle"]},
    {"key":35,"values":["round","circular"]},
    {"key":36,"values":["hexagon"]},
    {"key":37,"values":["octagon"]},
    {"key":38,"values":["triangle"]},
    {"key":39,"values":["square"]},
    {"key":40,"values":["rectangular"]},
    {"key":41,"values":["round","circular"]},
    {"key":42,"values":["hexagon"]},
    {"key":43,"values":["oval"]},
    {"key":44,"values":["octagon"]},
    {"key":45,"values":["square"]},
    {"key":46,"values":["specialty"]},
    {"key":48,"values":["boat"]},
    {"key":59,"values":["triangular"]},
    {"key":64,"values":["wedge"]},
    {"key":65,"values":["l-shaped"]},
    {"key":66,"values":["c-shaped"]},
];

window.sss.fuelTypes = [
    {"key":8,"values":["wood"]},
    {"key":9,"values":["propane"]},
    {"key":18,"values":["natural gas"]},
];

window.sss.liftSystems = [
    {"key":1,"values":["crank"]},
    {"key":2,"values":["manual","push up","push-up"]},
    {"key":3,"values":["pulley"]},
];

window.sss.exteriorMaterials = [
    {"key":1,"values":["steel"]},
    {"key":2,"values":["iron"]},
    {"key":3,"values":["stone"]},
    {"key":4,"values":["copper"]},
    {"key":5,"values":["aluminum"]},
    {"key":6,"values":["stainless steel"]},
    {"key":7,"values":["wood"]},
    {"key":8,"values":["wicker"]},
    {"key":9,"values":["fiberglass"]},
    {"key":10,"values":["concrete"]},
    {"key":11,"values":["glass"]},
    {"key":12,"values":["composite"]},
    {"key":13,"values":["porcelain"]},
    {"key":14,"values":["cast aluminum"]},
    {"key":15,"values":["hammered copper"]},
];
